# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aeb77d0ea0bfe2835b0bb17b777cc74dfcecb08202199dfc25d77ba6061a67d7b6aee50440a50b555628e8178626a401bf7b29832fea2cc0478d202afbbef345

test:
  secret_key_base: bcdf251d0856fb2f23c95d253915964021fc2103a20e4a0a20e53df1670a6823a841a7f69f0c94a76e6bc18b9b9350b68166148a64c72fcbac7e6da1905f9059

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
